# Definit ce que doivent savoir faire les classes qui sauvegardent session et preferences

from typing import Protocol, runtime_checkable

@runtime_checkable
class ISessionRepository(Protocol):
    def load_session(self) -> dict: ...
    def save_session(self, data: dict) -> bool: ...
    def clear_session(self) -> bool: ...
    def get_session_dir(self) -> str: ...

@runtime_checkable
class IPreferencesRepository(Protocol):
    def load(self) -> dict: ...
    def save(self, data: dict) -> bool: ...
